easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Answer
        - App\Entity\Message
        - App\Entity\Question
        - App\Entity\Result
        - App\Entity\User
